'use strict';

const htmlPdf = require('html-pdf-node');
const MarkdownIt = require('markdown-it');

const md = new MarkdownIt({ html: true, linkify: true, typographer: true });

const PDF_OPTIONS = {
  format: 'A4',
  margin: { top: '20mm', right: '15mm', bottom: '20mm', left: '15mm' },
};

/**
 * Wrap HTML content in a full styled page template.
 */
function wrapHtml(bodyHtml, title) {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>${escapeHtml(title || 'Document')}</title>
  <style>
    body {
      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
      font-size: 12px;
      line-height: 1.6;
      color: #333;
      max-width: 100%;
      padding: 0;
      margin: 0;
    }
    h1 { font-size: 24px; color: #1a1a2e; border-bottom: 2px solid #1a1a2e; padding-bottom: 8px; }
    h2 { font-size: 20px; color: #16213e; margin-top: 24px; }
    h3 { font-size: 16px; color: #0f3460; margin-top: 18px; }
    table { border-collapse: collapse; width: 100%; margin: 12px 0; }
    th, td { border: 1px solid #ddd; padding: 8px; text-align: left; font-size: 11px; }
    th { background-color: #1a1a2e; color: white; }
    tr:nth-child(even) { background-color: #f9f9f9; }
    .header { text-align: center; margin-bottom: 24px; }
    .header h1 { border-bottom: none; }
    .meta { color: #666; font-size: 11px; margin-bottom: 16px; }
    .category-section { margin-top: 24px; page-break-inside: avoid; }
    .cost-summary { background: #f0f4f8; padding: 12px; border-radius: 4px; margin: 12px 0; }
    .status-badge { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 10px; font-weight: bold; }
    .status-done { background: #d4edda; color: #155724; }
    .status-in_progress { background: #fff3cd; color: #856404; }
    .status-todo { background: #cce5ff; color: #004085; }
    .status-blocked { background: #f8d7da; color: #721c24; }
    code { background: #f4f4f4; padding: 2px 4px; border-radius: 3px; font-size: 11px; }
    pre { background: #f4f4f4; padding: 12px; border-radius: 4px; overflow-x: auto; }
    pre code { padding: 0; background: none; }
    ul, ol { padding-left: 20px; }
    .footer { text-align: center; font-size: 10px; color: #999; margin-top: 32px; border-top: 1px solid #eee; padding-top: 8px; }
  </style>
</head>
<body>
  ${bodyHtml}
  <div class="footer">Generated by De Novo NoMo &mdash; ${new Date().toLocaleDateString()}</div>
</body>
</html>`;
}

function escapeHtml(str) {
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function formatCurrency(amount) {
  if (amount == null) return '$0.00';
  return '$' + Number(amount).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}

/**
 * Generate a PDF buffer from raw HTML.
 *
 * @param {string} html - Full HTML string
 * @returns {Promise<Buffer>} PDF buffer
 */
async function generatePdf(html) {
  const file = { content: html };
  const buffer = await htmlPdf.generatePdf(file, PDF_OPTIONS);
  return buffer;
}

/**
 * Render a document version to PDF.
 *
 * @param {object} document - Document record with title, category, etc.
 * @param {object} version - Document version record with content_md
 * @returns {Promise<Buffer>} PDF buffer
 */
async function documentToPdf(document, version) {
  const contentHtml = md.render(version.content_md || '');
  const bodyHtml = `
    <div class="header">
      <h1>${escapeHtml(document.title)}</h1>
      <div class="meta">
        ${document.category ? `Category: ${escapeHtml(document.category)}` : ''}
        ${document.subcategory ? ` / ${escapeHtml(document.subcategory)}` : ''}
        &nbsp;&middot;&nbsp; Version ${version.version_number}
        &nbsp;&middot;&nbsp; ${new Date(version.created_at).toLocaleDateString()}
      </div>
    </div>
    ${contentHtml}
  `;

  const html = wrapHtml(bodyHtml, document.title);
  return generatePdf(html);
}

/**
 * Generate a decision report PDF for a location.
 *
 * @param {object} location - Location record
 * @param {Array} decisions - Array of decision records grouped by category
 * @returns {Promise<Buffer>} PDF buffer
 */
async function decisionReportToPdf(location, decisions) {
  // Group decisions by category
  const grouped = {};
  for (const d of decisions) {
    const cat = d.category || 'Uncategorized';
    if (!grouped[cat]) grouped[cat] = [];
    grouped[cat].push(d);
  }

  let totalOneTime = 0;
  let totalMonthly = 0;
  let totalAnnual = 0;

  for (const d of decisions) {
    totalOneTime += Number(d.estimated_cost_onetime) || 0;
    totalMonthly += Number(d.estimated_cost_monthly) || 0;
    totalAnnual += Number(d.estimated_cost_annual) || 0;
  }

  let sectionsHtml = '';
  for (const [category, items] of Object.entries(grouped)) {
    let rowsHtml = '';
    for (const item of items) {
      rowsHtml += `
        <tr>
          <td>${escapeHtml(item.item_key || '')}</td>
          <td>${escapeHtml(item.decision_summary || '')}</td>
          <td>${escapeHtml(item.selected_option || '')}</td>
          <td>${escapeHtml(item.status || '')}</td>
          <td style="text-align:right">${formatCurrency(item.estimated_cost_onetime)}</td>
          <td style="text-align:right">${formatCurrency(item.estimated_cost_monthly)}</td>
          <td style="text-align:right">${formatCurrency(item.estimated_cost_annual)}</td>
        </tr>`;
    }

    sectionsHtml += `
      <div class="category-section">
        <h2>${escapeHtml(category)}</h2>
        <table>
          <thead>
            <tr>
              <th>Item</th>
              <th>Decision</th>
              <th>Selected Option</th>
              <th>Status</th>
              <th>One-Time</th>
              <th>Monthly</th>
              <th>Annual</th>
            </tr>
          </thead>
          <tbody>${rowsHtml}</tbody>
        </table>
      </div>`;
  }

  const bodyHtml = `
    <div class="header">
      <h1>Decision Report</h1>
      <div class="meta">${escapeHtml(location.name)} &mdash; ${new Date().toLocaleDateString()}</div>
    </div>
    <div class="cost-summary">
      <strong>Cost Summary:</strong>
      One-Time: ${formatCurrency(totalOneTime)} |
      Monthly: ${formatCurrency(totalMonthly)} |
      Annual: ${formatCurrency(totalAnnual)}
    </div>
    ${sectionsHtml}
  `;

  const html = wrapHtml(bodyHtml, `Decision Report - ${location.name}`);
  return generatePdf(html);
}

/**
 * Generate a checklist PDF for a location.
 *
 * @param {object} location - Location record
 * @param {Array} items - Array of checklist item records
 * @returns {Promise<Buffer>} PDF buffer
 */
async function checklistToPdf(location, items) {
  // Group items by status
  const statusOrder = ['todo', 'in_progress', 'blocked', 'review', 'backlog', 'done'];
  const grouped = {};
  for (const item of items) {
    const status = item.status || 'backlog';
    if (!grouped[status]) grouped[status] = [];
    grouped[status].push(item);
  }

  let sectionsHtml = '';
  for (const status of statusOrder) {
    const group = grouped[status];
    if (!group || group.length === 0) continue;

    let rowsHtml = '';
    for (const item of group) {
      rowsHtml += `
        <tr>
          <td>${escapeHtml(item.title)}</td>
          <td>${escapeHtml(item.category || '')}</td>
          <td>${escapeHtml(item.priority || 'medium')}</td>
          <td>${item.due_date ? new Date(item.due_date).toLocaleDateString() : ''}</td>
          <td>${escapeHtml(item.assigned_to_name || '')}</td>
        </tr>`;
    }

    const statusLabel = status.replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());
    sectionsHtml += `
      <div class="category-section">
        <h2><span class="status-badge status-${status}">${statusLabel}</span> (${group.length})</h2>
        <table>
          <thead>
            <tr>
              <th>Title</th>
              <th>Category</th>
              <th>Priority</th>
              <th>Due Date</th>
              <th>Assigned To</th>
            </tr>
          </thead>
          <tbody>${rowsHtml}</tbody>
        </table>
      </div>`;
  }

  const bodyHtml = `
    <div class="header">
      <h1>Checklist</h1>
      <div class="meta">${escapeHtml(location.name)} &mdash; ${items.length} items &mdash; ${new Date().toLocaleDateString()}</div>
    </div>
    ${sectionsHtml}
  `;

  const html = wrapHtml(bodyHtml, `Checklist - ${location.name}`);
  return generatePdf(html);
}

module.exports = { generatePdf, documentToPdf, decisionReportToPdf, checklistToPdf };
